-- Persist account provenance on stored personal keys.
-- TRUE means the keypair was generated by Keycast during account provisioning.
ALTER TABLE personal_keys
ADD COLUMN IF NOT EXISTS is_generated BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_personal_keys_tenant_generated
ON personal_keys (tenant_id, is_generated);
